CUDA_VISIBLE_DEVICES=4 \
python -m pdb src/tasks/run_caption_VidSwinBert.py \
        --config src/configs/VidSwinBert/drama_default.json \
        --train_yaml drama/training_32frames.yaml \
        --val_yaml drama/testing_32frames.yaml \
        --per_gpu_train_batch_size 16 \
        --per_gpu_eval_batch_size 32 \
        --num_train_epochs 40 \
        --learning_rate 0.0004 \
        --max_num_frames 2 \
        --pretrained_2d 0 \
        --backbone_coef_lr 0.05 \
        --mask_prob 0.5 \
        --max_masked_token 45 \
        --zero_opt_stage 1 \
        --mixed_precision_method deepspeed \
        --deepspeed_fp16 \
        --gradient_accumulation_steps 1 \
        --loss_bbox_w 5 \
        --detr_aug \
        --seed $RANDOM \
        --output_dir ./output/test_caption